services:
  - type: web
    name: casanova-fashion
    runtime: python
    buildCommand: pip install -r requirements.txt && python mens_fashion/manage.py collectstatic --noinput && python mens_fashion/manage.py migrate --noinput
    startCommand: gunicorn core.wsgi --chdir=mens_fashion
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DEBUG
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
